
[general]
format=wav49|gsm|wav
serveremail=asterisk
attach=yes
skipms=3000
maxsilence=10
silencethreshold=128
maxlogins=3
emaildateformat=%A, %B %d, %Y at %r
pagerdateformat=%A, %B %d, %Y at %r
sendvoicemail=yes
charset=UTF-8
pollfreq=30
pollmailboxes=yes
envelope=yes
forcename=yes
forcegreetings=no
operator=yes
review=no
saycid=no
sayduration=yes
searchcontexts=no
tempgreetwarn=yes
usedirectory=yes
hidefromdir=no
moveheard=yes
smdienable=no
nextaftercmd=yes
emailsubject=PBX Voicemail Notification
emailbody=${VM_NAME},\n\nThere is a new voicemail in mailbox ${VM_MAILBOX}:\n\n\tFrom:\t${VM_CALLERID}\n\tLength:\t${VM_DUR} seconds\n\tDate:\t${VM_DATE}\n\nDial *98 to access your voicemail by phone.\nVisit /ucp to check your voicemail with a web browser.\n
fromstring=PBX Phone System
pagersubject=PBX Voicemail Notification
pagerbody=New ${VM_DUR} long msg in box ${VM_MAILBOX}\nfrom ${VM_CALLERID}, on ${VM_DATE}
pagerfromstring=PBX Phone System
pbxskip=no
maxgreet=60
maxmsg=100
minpassword=REDACTED
maxsecs=300
minsecs=1
imapgreetings=yes
imapclosetimeout=60
imapopentimeout=60
imapreadtimeout=60
imapwritetimeout=60
aliasescontext=pbxaliases

[zonemessages]
eastern=America/New_York|'vm-received' Q 'digits/at' IMp
central=America/Chicago|'vm-received' Q 'digits/at' IMp
central24=America/Chicago|'vm-received' q 'digits/at' H N 'hours'
military=Zulu|'vm-received' q 'digits/at' H N 'hours' 'phonetic/z_p'
european=Europe/Copenhagen|'vm-received' a d b 'digits/at' HM

[default]
1234=4242,Example Mailbox,root@localhost,,

[myaliases]
1234@devices=1234@default,,,,

[other]
1234=5678,Company2 User,root@localhost,,

